### ISSUE TITLE
`TinyAllocator` leak the allocated frames

### ISSUE THREAD

**Issue by asaadmohammed74** [phil-opp/blog_os#377] opened 2017-12-16 11:02 UTC
TinyAllocator allocate 3 frames from another allocator on construction but the problem is that once the TinyAllocator goes out of scope it doesn't deallocate the 3 frames it already allocated so this will leak memory

```
// next_free_frame is made public for the test

let mut allocator = AreaFrameAllocator::new(...);
assert!(allocator.next_free_frame.number == 0);

{
    let t = TinyAllocator::new(&mut allocator); // allocates 3 frames
} // t goes out of scope so now we lose access to the allocated frame

{
    let t = TinyAllocator::new(&mut allocator); // allocates 3 frames
} // t goes out of scope so now we lose access to the allocated frame

assert!(allocator.next_free_frame.number == 6);

```

**Comment by asaadmohammed74** [comment] 2017-12-16 11:43
a possible solution would be this
```
struct TinyAllocator<'a, Allocator: FrameAllocator + 'a> {
    frames: [Option<Frame>; 3],
    allocator: &'a mut Allocator,
}

impl<'a, Allocator: FrameAllocator + 'a> TinyAllocator<'a, Allocator> {
    fn new(allocator: &'a mut Allocator) -> Self {
        Self {
            frames: [
                allocator.allocate(),
                allocator.allocate(),
                allocator.allocate(),
            ],
            allocator: allocator,
        }
    }
}

impl<'a, Allocator: FrameAllocator + 'a> FrameAllocator for TinyAllocator<'a, Allocator> {
    fn allocate(&mut self) -> Option<Frame> {
        for frame_option in &mut self.frames {
            if frame_option.is_some() {
                return frame_option.take();
            }
        }
        None
    }

    fn deallocate(&mut self, frame: Frame) {
        for frame_option in &mut self.frames {
            if frame_option.is_none() {
                *frame_option = Some(frame);
                return;
            }
        }
        panic!("Tiny allocator can hold only 3 frames.");
    }
}

impl<'a, Allocator: FrameAllocator + 'a> core::ops::Drop for TinyAllocator<'a, Allocator> {
    fn drop(&mut self) {
        for frame in &mut self.frames {
            if frame.is_some() {
                self.allocator.deallocate(frame.take().unwrap());
            }
        }
    }
}
```

but i don't know how to integrate that into the existent code

**Comment by phil-opp** [comment] 2017-12-19 09:45
The problem is that we would hold a mutable reference to the original allocator, which means that we can't use the original allocator as long as the tiny allocator is live. So there wouldn't be an advantage over using the original allocator directly.

**Comment by 4e554c4c** [comment] 2017-12-19 18:26
See redox's implementation. Their implementation of a tiny allocator (called a page buffer I think) is marked as `#[must_use]`, the drop method panics, and there is a method that uses an allocator to consume the frames. This makes it impossible to leak frames without a panic.

**Comment by phil-opp** [comment] 2019-07-07 10:04
Closing as it only affects the first edition, which is no longer maintained.

**Closed by phil-opp** 2019-07-07 10:04 UTC
