### ISSUE TITLE
legacy asm! syntax is no longer supported when running cargo bootimage

### ISSUE THREAD

**Issue by leggettc18** [phil-opp/blog_os#807] opened 2020-05-20 01:31 UTC
I recently got a new laptop and went to set up my code for this project. I have the following steps listed in some notes I took for setup. Whenever I try to run `cargo bootimage` I get a bunch of errors that reads `error: legacy asm! syntax is no longer supported` Am I missing something or has something changed recently to cause some incompatability?

    Clone the repository and cd into it
    Install Rust
    Install build-essentials sudo apt install build-essentials
    Run rustc --version (will install rust-nightly based on rust-toolchain file)
    rustup component add rust-src
    rustup component llvm-tools-preview
    cargo install cargo-xbuild
    cargo install bootimage --version "^0.7.7"
    cargo bootimage
    sudo apt install qemu-kvm
    cargo xrun, it should run in a qemu window right now

I'm running Pop!_OS 20.04
`rustc --version` returns `rustc 1.45.0-nightly (3a7dfda40 2020-05-19)`

**Comment by phil-opp** [comment] 2020-05-20 08:06
Thanks for reporting this! The error is caused by a recent change in Rust, which renamed the `asm!` macro to `llvm_asm!`. The problem is that some of the dependencies still use the old `asm!` macro.

I try my best to update all the dependencies soon. Until then, you can try to use an older Rust nightly that still supports `asm!`.

**Comment by phil-opp** [comment] 2020-05-20 13:15
After #808 and #809, most uses of the deprecated `asm!` are replaced by the new `llvm_asm!` macro. I think the last remaining dependency with `asm!` in it is `pic8259_simple`, which is not maintained by be. I opened https://github.com/emk/toyos-rs/pull/6 to fix the issue and hope it gets merged and released soon.

**Comment by emk** [comment] 2020-05-20 18:09
You should be able to fix this by updating to `pic8259_simple = "0.2.0"`, which uses `llvm_asm!` but is otherwise compatible with version 0.1.x. Enjoy!

**Comment by leggettc18** [comment] 2020-05-20 22:58
I updated the bootloader dependency to version 0.9.3, and pic8259_simple to version 0.2.0, but I'm still getting the build errors. Am I missing something? Here is my Cargo.toml

```
[package]
name = "blog_os"
version = "0.1.0"
authors = ["Christopher Leggett <chris@leggett.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# the profile used for `cargo build`
[profile.dev]
panic = "abort" # disable stack unwinding on panic

# the profile used for `cargo build --release`
[profile.release]
panic = "abort" # disable stack unwinding on panic

[dependencies]
bootloader = { version = "0.9.3", features = ["map_physical_memory"]}
volatile = "0.2.6"
spin = "0.5.2"
x86_64 = "0.9.5"
uart_16550 = "0.2.0"
pic8259_simple = "0.2.0"
pc-keyboard = "0.5.0"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]

[package.metadata.bootimage]
test-args = ["-device", "isa-debug-exit,iobase=0xf4,iosize=0x04", "-serial", "stdio", "-display", "none"]
test-success-exit-code = 33 # (0x10 << 1) | 1
test-timeout = 300

[[test]]
name = "stack_overflow"
harness = false
```

**Comment by leggettc18** [comment] 2020-05-20 22:59
For reference, I hadn't finished the whole tutorial yet, I was partway through the Paging Implementation section.

**Comment by leggettc18** [comment] 2020-05-20 23:04
Nevermind! I just realized I missed updating the x86_64 dependency. Thanks for the help fixing this!

**Comment by phil-opp** [comment] 2020-05-21 07:35
Great to hear that it is working now!

**Closed** 2020-05-21 07:38 UTC
