### ISSUE TITLE
QEMU Bug in macOS 14: No "Hello, World" in `post-02` - just a black screen.

### ISSUE THREAD

**Issue by nskobelevs** [phil-opp/blog_os#1249] opened 2023-10-13 20:30 UTC
Having issue with "Hello, World!" now being displayed in QEMU.
Didn't work with my own code - tried the `post-02` branch as a sanity check but it didn't work there either. 

OS: `MacOS Sonoma 14.0`
rustc Version: `rustc 1.75.0-nightly (475c71da0 2023-10-11)`
QEMU Version: `8.1.1`

Video:

https://github.com/phil-opp/blog_os/assets/34107736/f5f207be-b469-4e58-9f98-c1ef20f27b18

**Comment by nskobelevs** [comment] 2023-10-13 20:33
`post-03` seems to work though:

<img width="832" alt="Screenshot 2023-10-13 at 21 32 51" src="https://github.com/phil-opp/blog_os/assets/34107736/3d8c1146-75f2-448d-a59b-7fe52476d9dc">

**Comment by AtomicGamer9523** [comment] 2023-10-13 22:10
There seems to be a trend of MacBooks not being able to run `post-02`.
Lemme see...

**Comment by Adamkob12** [comment] 2023-10-21 21:35
Having the same issue, with the same specs

**Comment by phil-opp** [comment] 2023-10-25 12:49
Thanks for reporting this issue! Are these M1/M2 Macs oder older ones?



> `post-03` seems to work though:

That's surprising.. Both branches are writing to the VGA text buffer at `0xb8000`, so I don't really understand how one of them works but the other doesn't...

**Comment by nskobelevs** [comment] 2023-10-25 12:56
> Are these M1/M2 Macs oder older ones?

These are the newer ones that started releasing in 2020 with Apple's new series of ARM chips ("Apple Silicon")

**Comment by phil-opp** [comment] 2023-10-25 13:32
I just tried to reproduce this issue on an M2 MacBook Air, but the `post-02` branch worked as expected for me.

**Comment by nskobelevs** [comment] 2023-10-25 16:14
It's unlikely to be an issue specifically with M1 vs M2 given architecture is the same as far as I know.

What was the OS, QEMU & rustc versions on the M2 you used? - perhaps something is different there

**Comment by qwerzl** [comment] 2023-10-31 13:40
Same here - the `post-02` branch only outputs a blank screen. I'm with an M1Pro Macbook Pro.

Here are the versions that I'm using:
rustc: `rustc 1.75.0-nightly (31bc7e2c4 2023-10-30)`
QEMU: `8.1.2`
OS: `macOS Sonoma Version 14.0 Beta (23A5312d)`

**Comment by rprovodenko** [comment] 2023-11-19 20:47
Not sure what's going on exactly, but the arithmetics for calculating the offsets is wrong. The text ends up being too high up and you can't see it
If you change the code to this, it works:
```
#[no_mangle]
pub extern "C" fn _start() -> ! {
    let vga_buffer = 0xb8000 as *mut u8;

    for (i, &byte) in HELLO.iter().enumerate() {
        unsafe {
            let line_offset: isize = 80 * 40;
            let char_offset_within_line: isize = i as isize * 2;
            let color_offset_within_line: isize = i as isize * 2 + 1;
            let char_offset = char_offset_within_line + line_offset;
            let color_offset = color_offset_within_line + line_offset;


            *vga_buffer.offset(char_offset) = byte;
            *vga_buffer.offset(color_offset) = 0xb;
        }
    }

    loop {}
}
```

<img width="784" alt="image" src="https://github.com/phil-opp/blog_os/assets/60982217/cfd04c99-3463-4a71-95a4-2b0d7259b2ce">

If you change the `line_offset` to
```
let line_offset: isize = 80 * 4;
```
you get: 


<img width="762" alt="image" src="https://github.com/phil-opp/blog_os/assets/60982217/59b44cdd-37d3-45ab-8648-363d1111c00e">

So it seems apparent that the assumption that the width of a column is `80` chars. 

However, if you change the `line_offset` to `80 * 45` you get this:

<img width="782" alt="image" src="https://github.com/phil-opp/blog_os/assets/60982217/3b71a1b6-d6f1-4fe0-9063-22dfa94c3b22">

The text appears mid-column, which I don't have an explanation for.

**Comment by rprovodenko** [comment] 2023-11-19 21:09
https://github.com/phil-opp/blog_os/pull/1252 is the fix

**Comment by AtomicGamer9523** [comment] 2023-11-20 00:26
This seems to be related to an issue on how Qemu works on MacOS. Specifically some bug, only visible in certain versions of Qemu...

Qemu Versions affected (going from comments): `8.1.1` and `8.1.2`. Both of these are obtainable from [Homebrew](https://formulae.brew.sh/formula/qemu). [MacPorts](https://ports.macports.org/port/qemu/) seems to be outdated and only hold the `8.0.5` version... could anybody test to see if that one is affected ?

**Comment by phil-opp** [comment] 2023-11-21 15:29
> What was the OS, QEMU & rustc versions on the M2 you used? - perhaps something is different there

I'm also using `8.1.2` installed through homebrew. I just tried it again with the latest rustc nightly (`2023-11-20`),  but I still see the expected output on the `post-02` branch. I'm on macOS `13.5.2`. 




> I've got the same problem, just figured out that the first line with "Hello world" is visible in full screen mode.

Interesting! Maybe it's just a window sizing bug then. Are you all on MacOS 14?

**Comment by AtomicGamer9523** [comment] 2023-11-21 16:27
> > What was the OS, QEMU & rustc versions on the M2 you used? - perhaps something is different there
> 
> I'm also using `8.1.2` installed through homebrew. I just tried it again with the latest rustc nightly (`2023-11-20`),  but I still see the expected output on the `post-02` branch. I'm on macOS `13.5.2`. 
> 
> 
> 
> 
> > I've got the same problem, just figured out that the first line with "Hello world" is visible in full screen mode.
> 
> Interesting! Maybe it's just a window sizing bug then. Are you all on MacOS 14?
> 
> 

Quite interesting... so this verifies that it is not the os code. It is an issue related to Qemu on MacOS.

**Comment by that-ben** [comment] 2023-11-24 17:14
<img width="905" alt="Screenshot 2023-11-24 at 12 12 57 PM" src="https://github.com/phil-opp/blog_os/assets/13210399/03d64585-76c0-48de-9470-87d572a9bf57">

**Comment by wzslr321** [comment] 2023-12-21 00:34
> The line width is different (`160`, not `80` as the code in post 3 assumes), and the first line is invisible. If you change the function to
> 
> ```
> #[no_mangle]
> pub extern "C" fn _start() -> ! {
>     let vga_buffer = 0xb8000 as *mut u8;
> 
>     for (i, &byte) in HELLO.iter().enumerate() {
>         unsafe {
>             let line_offset: isize = 160 * 2;
>             let char_offset_within_line: isize = i as isize * 2;
>             let color_offset_within_line: isize = i as isize * 2 + 1;
>             let char_offset = char_offset_within_line + line_offset;
>             let color_offset = color_offset_within_line + line_offset;
> 
> 
>             *vga_buffer.offset(char_offset) = byte;
>             *vga_buffer.offset(color_offset) = 0xb;
>         }
>     }
> 
>     loop {}
> }
> ```
> 
> You get the first fully visible line
> 
> <img alt="image" width="797" src="https://private-user-images.githubusercontent.com/60982217/284089689-8746c3d2-5061-4978-8bc2-b8a93ce6b968.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMTkwNDksIm5iZiI6MTcwMzExODc0OSwicGF0aCI6Ii82MDk4MjIxNy8yODQwODk2ODktODc0NmMzZDItNTA2MS00OTc4LThiYzItYjhhOTNjZTZiOTY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDAwMzIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzNmFkODEwM2IwYzgzNjFkYjJlMjk0ZWYyY2I4ZmI5NTBjYWYyNDE1Njg0MmI5MDgwODE0ZTg5OGJmZGM5NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a6Vw3pITut0x2ZBwbyxVd87hm51_qJjOUB_XnT6MevE">
> And:
> 
> ```
> let line_offset: isize = 160 * 24;
> ```
> 
> gives
> 
> <img alt="image" width="841" src="https://private-user-images.githubusercontent.com/60982217/284089749-6eab7691-3a1a-49f5-818d-c9d7536efaef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMTkwNDksIm5iZiI6MTcwMzExODc0OSwicGF0aCI6Ii82MDk4MjIxNy8yODQwODk3NDktNmVhYjc2OTEtM2ExYS00OWY1LTgxOGQtYzlkNzUzNmVmYWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDAwMzIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkMjA0NmZjYzQ5MmZlNDAyNWFjNDkwMjhhMjEwZGQ4M2JmZjc5MDQ1NTBkOTdlNmIxYTExZjUyM2NmODg4ZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vr7tuzm2YO2O7q_A1jJIfGLQng5yFDUe61utp4rK5QI">
> Looking at the code of `post 3` I see that it starts writing from column `23`. So yeah, that's the problem. Maybe qemu has an ability to specify different settings for VGA, but it seems that it just doesn't display the `0` line with in the current setup

Works for me, thanks!

**Comment by yasinldev** [comment] 2024-01-20 12:39
> > The line width is different (`160`, not `80` as the code in post 3 assumes), and the first line is invisible. If you change the function to
> > ```
> > #[no_mangle]
> > pub extern "C" fn _start() -> ! {
> >     let vga_buffer = 0xb8000 as *mut u8;
> > 
> >     for (i, &byte) in HELLO.iter().enumerate() {
> >         unsafe {
> >             let line_offset: isize = 160 * 2;
> >             let char_offset_within_line: isize = i as isize * 2;
> >             let color_offset_within_line: isize = i as isize * 2 + 1;
> >             let char_offset = char_offset_within_line + line_offset;
> >             let color_offset = color_offset_within_line + line_offset;
> > 
> > 
> >             *vga_buffer.offset(char_offset) = byte;
> >             *vga_buffer.offset(color_offset) = 0xb;
> >         }
> >     }
> > 
> >     loop {}
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You get the first fully visible line
> > <img alt="image" width="797" src="https://private-user-images.githubusercontent.com/60982217/284089689-8746c3d2-5061-4978-8bc2-b8a93ce6b968.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMTkwNDksIm5iZiI6MTcwMzExODc0OSwicGF0aCI6Ii82MDk4MjIxNy8yODQwODk2ODktODc0NmMzZDItNTA2MS00OTc4LThiYzItYjhhOTNjZTZiOTY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDAwMzIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzNmFkODEwM2IwYzgzNjFkYjJlMjk0ZWYyY2I4ZmI5NTBjYWYyNDE1Njg0MmI5MDgwODE0ZTg5OGJmZGM5NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a6Vw3pITut0x2ZBwbyxVd87hm51_qJjOUB_XnT6MevE">
> > And:
> > ```
> > let line_offset: isize = 160 * 24;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > gives
> > <img alt="image" width="841" src="https://private-user-images.githubusercontent.com/60982217/284089749-6eab7691-3a1a-49f5-818d-c9d7536efaef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMTkwNDksIm5iZiI6MTcwMzExODc0OSwicGF0aCI6Ii82MDk4MjIxNy8yODQwODk3NDktNmVhYjc2OTEtM2ExYS00OWY1LTgxOGQtYzlkNzUzNmVmYWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDAwMzIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkMjA0NmZjYzQ5MmZlNDAyNWFjNDkwMjhhMjEwZGQ4M2JmZjc5MDQ1NTBkOTdlNmIxYTExZjUyM2NmODg4ZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vr7tuzm2YO2O7q_A1jJIfGLQng5yFDUe61utp4rK5QI">
> > Looking at the code of `post 3` I see that it starts writing from column `23`. So yeah, that's the problem. Maybe qemu has an ability to specify different settings for VGA, but it seems that it just doesn't display the `0` line with in the current setup
> 
> Works for me, thanks!

thanks for the solution

**Comment by NightProg** [comment] 2024-01-28 08:49
> The line width is different (`160`, not `80` as the code in post 3 assumes), and the first line is invisible. If you change the function to
> 
> ```
> #[no_mangle]
> pub extern "C" fn _start() -> ! {
>     let vga_buffer = 0xb8000 as *mut u8;
> 
>     for (i, &byte) in HELLO.iter().enumerate() {
>         unsafe {
>             let line_offset: isize = 160 * 2;
>             let char_offset_within_line: isize = i as isize * 2;
>             let color_offset_within_line: isize = i as isize * 2 + 1;
>             let char_offset = char_offset_within_line + line_offset;
>             let color_offset = color_offset_within_line + line_offset;
> 
> 
>             *vga_buffer.offset(char_offset) = byte;
>             *vga_buffer.offset(color_offset) = 0xb;
>         }
>     }
> 
>     loop {}
> }
> ```
> 
> You get the first fully visible line
> <img alt="image" width="797" src="https://private-user-images.githubusercontent.com/60982217/284089689-8746c3d2-5061-4978-8bc2-b8a93ce6b968.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MzE4NjAsIm5iZiI6MTcwNjQzMTU2MCwicGF0aCI6Ii82MDk4MjIxNy8yODQwODk2ODktODc0NmMzZDItNTA2MS00OTc4LThiYzItYjhhOTNjZTZiOTY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDA4NDYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhOWZkNmNhYzZmZjQzZDQ5MzQyMTNkMzFkNmJhZTQyMWM3MjQ0NTg5YjQ4ODVkODk1N2YwZTlhMmI1ODE4ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WUbZegj_YwfHI5USfa90qkAxrrRnx4woUjLvhnOrWHA">
> 
> And:
> 
> ```
> let line_offset: isize = 160 * 24;
> ```
> 
> gives
> <img alt="image" width="841" src="https://private-user-images.githubusercontent.com/60982217/284089749-6eab7691-3a1a-49f5-818d-c9d7536efaef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MzE4NjAsIm5iZiI6MTcwNjQzMTU2MCwicGF0aCI6Ii82MDk4MjIxNy8yODQwODk3NDktNmVhYjc2OTEtM2ExYS00OWY1LTgxOGQtYzlkNzUzNmVmYWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDA4NDYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzNDUyZDQyZjNkYzQ4MmQzYjc3MDYxYTFkMTFmOGE2NzBkNTYxNTk5ZWUwY2QyMjhmMTAzMThiNDJlYzU2MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l_tafUJchnAU1A7B1k7nSpPuleqp8TNM8U_AJ-irn-E">
> 
> Looking at the code of `post 3` I see that it starts writing from column `23`. So yeah, that's the problem. Maybe qemu has an ability to specify different settings for VGA, but it seems that it just doesn't display the `0` line with in the current setup

Thanks that work for me

**Comment by AtomicGamer9523** [comment] 2024-02-27 00:00
I have opened this issue: https://gitlab.com/qemu-project/qemu/-/issues/1994

```
It's an API difference between Sonoma and earlier macOS versions NSView documented in https://developer.apple.com/documentation/macos-release-notes/appkit-release-notes-for-macos-14.

Sonoma set NSView.clipsToBounds to false by default and it was true in earlier versions.
```

DrDonk seems to he working on it, it will hopefully be in the upstream Qemu soon...

**Comment by phil-opp** [comment] 2024-02-27 06:35
@AtomicGamer9523 Thanks a lot, that is great news!

**Comment by AtomicGamer9523** [comment] 2024-03-18 22:29
Good news: [f5af8027](https://gitlab.com/qemu-project/qemu/-/commit/f5af80271aad356233b2bea2369b3b2211fa395d) was merged. It is now fixed in nightly and will be included in the 9.0 stable release

**Comment by AtomicGamer9523** [comment] 2024-04-05 21:01
To anybody that stumbled upon this via a google search or because of a pinned comment, here's a quick rundown:
 
- **If you are not on MacOS, this should not affect you**
- **If you are not using Qemu, this should not affect you**
- **If you are on MacOS version 13 and bellow, this should not affect you**

Now, if you are on MacOS newer than than version 14, and you are using Qemu, listen up.
There is a window-sizing bug in Qemu that will shift text up, preventing you from being able to see some of it.
It is fixed in Qemu `9.0`. Bellow are package managers and latest version of Qemu available:
- [ ] [Homebrew](https://formulae.brew.sh/formula/qemu) (`8.2.1`)
- [ ] [MacPorts](https://ports.macports.org/port/qemu/) (`8.2.2`)

**Comment by phil-opp** [comment] 2024-04-30 14:48
Looks like both homebrew and macPorts provide v0.9 now, do I see that right?

**Comment by AtomicGamer9523** [comment] 2024-04-30 18:59
> Looks like both homebrew and macPorts provide v0.9 now, do I see that right?

Correct, updating my comment

**Comment by phil-opp** [comment] 2024-04-30 20:20
Great! Yes, I think we can close this then. I'll keep it pinned for a while, so it should still be visible enough.

**Closed by phil-opp** 2024-04-30 20:20 UTC
