### ISSUE TITLE
Wrong file name x86_64-blog_os.json

### ISSUE THREAD

**Issue by BORN2LOSE** [phil-opp/blog_os#406] opened 2018-03-10 14:31 UTC
When compiling with this file name `x86_64-blog_os.json` occurs expected errors:
```bash
> RUST_TARGET_PATH=(pwd) xargo build --target x86_64-unknown-blog_os
error: Error loading target specification: Could not find specification for target "x86_64-unknown-blog_os"
```

You need to rename into `x86_64-unknown-blog_os.json` to compile core lib.
> 02-minimal-rust-kernel/index.md

**Comment by Herbstein** [comment] 2018-03-10 15:59
I'm still getting the same error even when renaming the JSON file

**Comment by phil-opp** [comment] 2018-03-10 16:22
The syntax for the environment variable might differ between shells. Try wrapping the `pwd` in backticks instead of parantheses or setting the variable to the current directory explicitly.

**Comment by Herbstein** [comment] 2018-03-10 17:09
Even when setting the path directly the command will fails with the same
error.

**Comment by fdb-hiroshima** [comment] 2018-03-10 22:47
Linked : on line 225 to 229 there is an inconsistency between the command run and the error we get, command target is `x86_64-unknown-blog_os` but error is about `x86_64-blog_os`
This probably come from the first version, where `x86_64-blog_os` was the norm.

**Comment by phil-opp** [comment] 2018-03-11 10:51
I updated the text so that `x86_64-blog_os` is used everywhere in 77522e7. Thanks for reporting @BORN2LOSE and @fdb-hiroshima!

@Herbstein Are you still experiencing this error? If so, could you try to use the `bootimage` tool that is decribed [further down in the post](https://os.phil-opp.com/minimal-rust-kernel/#creating-a-bootimage)? If this works, the issue is related to setting the environment variable, else it could be a typo in the `json` file name or that the file is at a wrong location (i.e. not next to the `Cargo.toml`).

**Comment by Herbstein** [comment] 2018-03-11 18:54
I was doing things through WSL, which is where it didn't work. On the exact same files `bootimage` does work on windows.

**Comment by phil-opp** [comment] 2018-03-13 15:05
@Herbstein I just merged #413. Seems like the syntax was wrong in the post. Could you try `RUST_TARGET_PATH=$(pwd) xargo build --target x86_64-blog_os` with a target file named `x86_64-blog_os.json`? (The target file name doesn't matter, it is just the name that you need to use in the command.)

**Comment by phil-opp** [comment] 2018-03-13 17:34
Perfect!

> Now I just need to figure out why `bootimage` doesn't want to install. (Gives me an error saying OpenSSL isn't found while building a dependency. I know for a fact that it is)

Which dependency? Maybe we can get rid of it..

**Comment by Herbstein** [comment] 2018-03-13 17:39
The dependency is `openssl-sys`. I've installed both the library and the dev package through `apt`.

**Comment by Herbstein** [comment] 2018-03-13 17:39
Doh, nevermind. I haven't got `pkg-config` installed.

**Comment by phil-opp** [comment] 2018-03-14 17:44
Ok cool! Seems like we can close this issue then. Thanks you all for your feedback!

**Closed by phil-opp** 2018-03-14 17:44 UTC
