### ISSUE TITLE
Making blog fully multilingual

### ISSUE THREAD

**Issue by hamidrezakp** [phil-opp/blog_os#895] opened 2020-12-31 09:28 UTC
Hi.
The blog currently have supports multi languages but its just posts that are available in other languages.
I think it is so much better if we can have the whole blog texts in other languages. but this is a lot of work and will make template way too complex.

So i propose to add support for translate files. There is some literal texts in templates and they can be read from a `toml` file that contains the translations.

Also we have another problem for languages that have right-to-left layout like Persian. We need to add support for right-to-left in template. This of course is complex and we can start by Home page.
For this to work, we need to somehow in config file specify which language have which layout, i think we can't use `language` array in config file and there must be a dictionary that contains translation file, layout model and name of language.

I like to help making this happen, let me know your opinion on this.

**Comment by phil-opp** [comment] 2021-01-02 17:23
I think the best way to do this is to make the contents of the index page a normal markdown page. I started implementing this in https://github.com/phil-opp/blog_os/pull/899. Since markdown supports inline HTML, it's easily possible to add the `right-to-left` class where needed.

For translations of shorter sequences such as single headings or the "read more" links we can use the [translations table in the config.toml file](https://github.com/phil-opp/blog_os/blob/68d12a783992b17972a0582ab38bf7c589705db0/blog/config.toml#L36-L49).

**Comment by hamidrezakp** [comment] 2021-01-02 18:36
Good idea, this way we can translate any page so easily.
I will start translating index page as soon as you complete #899.
Thank you for your great work!

**Comment by phil-opp** [comment] 2021-01-03 09:22
It's probably easier to spot all the places that need a translation while doing the translation. So I would merge #899 as is for now and then you can decide which parts to translate. Would that be ok with you?

**Comment by hamidrezakp** [comment] 2021-01-03 10:38
Sounds good to me.

**Comment by phil-opp** [comment] 2021-01-03 13:31
Ok, I merged the PR (after reverting the example translation file).

**Comment by hamidrezakp** [comment] 2021-01-03 15:39
I made some changes in #901 but we have a problem, it is hard to translate texts that have much HTML tags or macros in them. the reason is that texts in `translations` array will not be rendered.
for example:
 ```
 If you want to work with me, reach out on <a href = \"https://www.linkedin.com/in/phil-opp/\">LinkedIn</a> or write me at <a href=\"mailto:job@phil-opp.com\">job@phil-opp.com</a>.
 ```
 One (not nice) solution is to split text into several shorter texts that don't have any HTML tag.
I prefer to use something like `.md` file but it will also make blog file so complex.
Do you have any suggestions?

**Comment by phil-opp** [comment] 2021-01-03 15:53
I think you should be able to apply the `safe` filter after `trans` to have the HTML rendered.

Also, I think that we shouldn't translate the "about me" section you cited as it gives the wrong impression that I understand all these languages.

**Comment by hamidrezakp** [comment] 2021-01-03 16:49
Oh, thanks i didn't know that.
Yes you are right, i will change it.

**Comment by hamidrezakp** [comment] 2021-01-07 10:27
@woodyZootopia @JohnTitor
@luojia65 @Rustin-Liu
@wusyong
We are doing a full blog multilingual support and currently some of its essential are ready.
I also done some changes and add translations for Persian in  #901 that will make index page and some other texts in posts page translatable. as soon as the #901 get merged into master, you can start translate yourself languages of blog.

It would be nice if you can translate and help blog be fully multilingual in current languages.
Thank you.

**Comment by GuillaumeDIDIER** [comment] 2021-01-07 10:33
Is anyone interested in a French translation / has started one ? (I might look into helping out with one).

**Comment by hamidrezakp** [comment] 2021-01-08 10:07
The #901 is merged thanks to @phil-opp.
Other languages now can have index and posts full translations.

**Comment by hamidrezakp** [comment] 2021-01-08 10:12
@phil-opp I noticed that every language have separated comments issue in Github, so we do not need the "Please leave your comments in English if possible. " in comments section. right?
I mean that people can speak their language in their translations.

**Comment by phil-opp** [comment] 2021-01-08 10:23
The problem is that I don't understand these languages, so I can't respond if someone reports an issue or has a question. Of course it would work if someone else managed these foreign comments, but that's difficult to organize reliably.

Perhaps we could change the wording a bit to clarify this. Maybe something like "Note that the original author only understands English, so he won't be able to reply to comments in other languages"?

**Comment by hamidrezakp** [comment] 2021-01-08 10:45
You are right. we can add this text to clarify. It would help others.

**Comment by phil-opp** [comment] 2021-02-05 11:10
This is implemented for the Persian and Japanese translations now. Only the Chinese translations are missing.

cc @luojia65, @hi-rustin, @wusyong: Maybe someone of you has time to update the page description for the Chinese translations? The files that need to be updated for this are `blog/content/_index.zh-*.md` and the `translations.zh-*` tables in `blog/config.toml`.

**Comment by hi-rustin** [comment] 2021-03-30 12:01
> This is implemented for the Persian and Japanese translations now. Only the Chinese translations are missing.
> 
> cc @luojia65, @hi-rustin, @wusyong: Maybe someone of you has time to update the page description for the Chinese translations? The files that need to be updated for this are `blog/content/_index.zh-*.md` and the `translations.zh-*` tables in `blog/config.toml`.

I will working on this.

**Closed** 2021-04-02 12:31 UTC
