### ISSUE TITLE
Error when compiling using bootimage 

### ISSUE THREAD

**Issue by wwestlake** [phil-opp/blog_os#522] opened 2019-01-18 01:45 UTC
I have installed the nightly build, xbuild, and bootimage and checked that the versions all seem correct.  Everything works up to the point of creating an image, the project even builds with cargo xbuild --target...but when I run bootimage build --target ... I get this error, here is the backtrace:

```
wwestlake@kali:~/Projects/rust/os-dev$ RUST_BACKTRACE=1 bootimage build --target x86_64-hacker-os.json
thread 'main' panicked at 'Could not read crate name from cargo metadata', src/libcore/option.rs:1038:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: rust_begin_unwind
             at src/libstd/panicking.rs:312
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::option::expect_failed
             at src/libcore/option.rs:1038
   9: bootimage::build::build_impl
  10: bootimage::build::build
  11: bootimage::main
  12: std::rt::lang_start::{{closure}}
  13: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  14: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:92
  15: std::rt::lang_start_internal
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  16: main
  17: __libc_start_main
  18: _start

```

**Comment by phil-opp** [comment] 2019-01-18 10:53
Thanks for reporting. Do you mind opening an issue in the rust-osdev/bootimage repository for this? Also, I can't reproduce this issue. Could you share a code example that causes this issue?

**Comment by wwestlake** [comment] 2019-01-19 00:37
I will do both

**Comment by wwestlake** [comment] 2019-01-19 01:01
I have opened an issue on rust-osdev/bootimage and attached a tar.gz file with the code that causes the issue.  I tested it again to make sure and got the same error.  It also doesn't matter if I run bootimage from the workspace folder or the project folder I get the same error, but when I separate the project from the workspace it runs fine.

**Comment by phil-opp** [comment] 2019-01-20 17:33
Thanks a lot!

Closing in favor of https://github.com/rust-osdev/bootimage/issues/28.

**Closed by phil-opp** 2019-01-20 17:33 UTC
