### ISSUE TITLE
Some comment/question for “Set Up Rust”

### ISSUE THREAD

**Issue by matematikaadit** [phil-opp/blog_os#248] opened 2016-10-27 11:39 UTC
Hello, newcomer here. Thanks for the wonderful series.

A comment and question about this post http://os.phil-opp.com/set-up-rust.html

I'm using Rust rustc 1.14.0-nightly (aef18be1b 2016-10-25), the part about missing fmod and fmodf functions seems doesn't happen to me. Probably it's already fixed?

Also, it's about the cargo part. Probably mentions/shows that `cargo` has been added in `.PHONY` target, and also `cargo clean` added in `clean` target in the Makefile (Tho, haven't checked if it's mentioned in the future post).

**Comment by phil-opp** [comment] 2016-10-28 10:46
Thanks a lot for the report!

--

> the part about missing fmod and fmodf functions seems doesn't happen to me. Probably it's already fixed?

I can no longer reproduce the linker error either. Thanks for the pointer! It seems like rustc no longer generates/needs those functions…

However, the most recent post (“Returning from Exceptions”) fails without `--gc-sections`:

```
target/test/debug/libblog_os.a(core.0.o): In function `_$LT$f32$u20$as$u20$core..num..dec2flt..rawfp..RawFloat$GT$::from_int::h2f372ef48b3d835a':
core.cgu-0.rs:(.text._ZN59_$LT$f32$u20$as$u20$core..num..dec2flt..rawfp..RawFloat$GT$8from_int17h2f372ef48b3d835aE+0x2): undefined reference to `__floatundisf'
target/test/debug/libblog_os.a(core.0.o): In function `_$LT$f64$u20$as$u20$core..num..dec2flt..rawfp..RawFloat$GT$::from_int::hbecf33dde444988c':
core.cgu-0.rs:(.text._ZN59_$LT$f64$u20$as$u20$core..num..dec2flt..rawfp..RawFloat$GT$8from_int17hbecf33dde444988cE+0x2): undefined reference to `__floatundidf'
Makefile:43: recipe for target 'build/kernel-x86_64.bin' failed
```

I guess it's because of the custom target: The “Set Up Rust” code shows the same error when compiled for a custom target (even without a `feature` key).

So I can think of two possible solutions:

1. Find a different motivation for `--gc-sections` in “Set Up Rust” (e.g. binary size). Most projects should use `--gc-sections` (AFAIK rustc uses it by default for executables), so it's good to introduce it early.
2. Remove any mention of `--gc-sections` from “Set Up Rust” and only introduce it when the error occurs for the first time in “Returning from Exceptions”. This would fit better into our “don't fix problems before they occur” approach.

--

> Probably mention/show that cargo has been added in .PHONY target, and also cargo clean added in clean target in the Makefile

Good catch! Yeah, we should really do that.

**Comment by ahmedcharles** [comment] 2017-03-08 11:10
In my incarnation of this kernel, I setup xargo in the first commit that adds rust with the custom target because having a sane build system and cross compile story is important from the beginning. Rather than viewing it as fixing a problem before it starts, I'd view it as doing the right thing from the beginning.

**Comment by phil-opp** [comment] 2017-03-22 14:20
@ahmedcharles When I wrote the Set Up Rust post, `xargo` didn't exist and cross compiling was much more difficult. So I decided to use the standard `x86_64-unknown-linux-gnu` target as long as possible. I'm currently working on a complete overhaul of the blog and I think the new version will use `xargo` right from the start.

**Comment by phil-opp** [comment] 2019-07-06 17:20
Closing since this was about the first edition, which is no longer maintained.

**Closed by phil-opp** 2019-07-06 17:20 UTC
